# Generated by Django 3.0.5 on 2020-04-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date_start', models.DateField(auto_now_add=True)),
                ('date_end', models.DateTimeField()),
            ],
        ),
    ]
