# Generated by Django 3.0.5 on 2020-05-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todotask_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todotask',
            options={'ordering': ('date_end',)},
        ),
    ]
